default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: mysecretpassword
  host: localhost
  port: 5432

development:
  <<: *default
  database: postgres

test:
  <<: *default
  database: fake_instagram_api_test

production:
  primary: &primary_production
    <<: *default
    database: fake_instagram_api_production
    username: fake_instagram_api
    password: <%= ENV["FAKE_INSTAGRAM_API_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: fake_instagram_api_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: fake_instagram_api_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: fake_instagram_api_production_cable
    migrations_paths: db/cable_migrate
